http:
  host: 'localhost'
  port: 3000

database:
  mysql:
    host: 'theta-db.c9jaiicvcvbn.us-east-1.rds.amazonaws.com'
    port: 3306
    user: 'admin'
    password: 'Clapham101_'
    database: 'theta'
    synchronize: false
